import type { Metadata } from 'next';
import { Noto_Sans_KR } from 'next/font/google';
import 'reset-css';
import '../styles/globals.css';

export const notoSansKr = Noto_Sans_KR({
  subsets: ['latin'], // 꼭 'korean' 지정해야 한글 포함됨!
  weight: ['400', '700'], // 원하는 굵기만 불러오기 (파일 용량↓)
  variable: '--font-noto-kr', // CSS 변수 등록 (선택)
  display: 'swap', // 글자 깜빡임 방지
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body className={`${notoSansKr.variable} `}>{children}</body>
    </html>
  );
}
