import type { Metadata } from 'next';
import 'reset-css';
import '@/styles/globals.scss';
import '@/styles/global.css';
import styles from './layout.module.scss';
import Header from '@/components/Header/Header';
import Footer from '@/components/Footer/Footer';

export const metadata: Metadata = {
  title: '플래시니티',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body>
        <div className={styles.wrapper}>
          <Header />
          <div className="layout flex-1">{children}</div>
          <Footer />
        </div>
      </body>
    </html>
  );
}
